/**
 * Export utilities for VibeCheck reports
 */

/**
 * Generates a Markdown report from analysis results
 */
export function generateMarkdownReport(text, report, stats) {
    const now = new Date();
    const timestamp = now.toLocaleString('en-US', {
        dateStyle: 'long',
        timeStyle: 'short'
    });

    let md = `# VibeCheck Analysis Report\n\n`;
    md += `**Generated:** ${timestamp}\n\n`;
    md += `---\n\n`;

    // Summary
    md += `## Summary\n\n`;
    md += `| Metric | Count |\n`;
    md += `|--------|-------|\n`;
    md += `| Total Claims | ${stats.total} |\n`;
    md += `| Verified | ${stats.verified} |\n`;
    md += `| Hallucinations | ${stats.hallucinations} |\n`;
    md += `| Suspicious | ${stats.suspicious} |\n\n`;

    // Original Text
    md += `## Original Text\n\n`;
    md += `> ${text.replace(/\n/g, '\n> ')}\n\n`;

    // Detailed Analysis
    md += `## Detailed Analysis\n\n`;

    if (report?.claims) {
        report.claims.forEach((claim, index) => {
            const statusEmoji = {
                VERIFIED: '✅',
                HALLUCINATION: '❌',
                SUSPICIOUS: '⚠️',
                OPINION: '💭'
            }[claim.status] || '❓';

            md += `### Claim ${index + 1} ${statusEmoji} ${claim.status}\n\n`;
            md += `**Original:** "${claim.original_text}"\n\n`;
            md += `**Type:** ${claim.type}\n\n`;
            md += `**Reasoning:** ${claim.reasoning}\n\n`;
            md += `**Confidence:** ${claim.confidence_score}%\n\n`;

            if (claim.correction) {
                md += `**Correction:** ${claim.correction}\n\n`;
            }

            if (claim.source_url) {
                md += `**Source:** [${claim.source_url}](${claim.source_url})\n\n`;
            }

            md += `---\n\n`;
        });
    }

    md += `\n*Report generated by VibeCheck AI*\n`;

    return md;
}

/**
 * Downloads content as a file
 */
export function downloadFile(content, filename, mimeType = 'text/markdown') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Exports the analysis report as Markdown
 */
export function exportAsMarkdown(text, report, stats) {
    const markdown = generateMarkdownReport(text, report, stats);
    const timestamp = new Date().toISOString().split('T')[0];
    downloadFile(markdown, `vibecheck-report-${timestamp}.txt`, 'text/plain');
}
